### ISSUE TITLE
Asteroid Field tool just crashes the whole tool 

### ISSUE THREAD

**Issue by isGoosey** [mmusu3/SEToolbox#7]
**SEToolbox Version: Newest 10/26/24
**SE Version: Newest 10/26/24

### Issue Description
Asteroid Field tool just crashes the whole SEtoolbox

### Steps to Reproduce
Asteroid Field tool try and use it

### SEToolbox Log File
```
2024-10-26 23:18:45,969 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Users\%USERNAME%\Desktop\SEToolbox-1.205.024.1\SEToolbox.exe
CommandLine: "C:\Users\%USERNAME%\Desktop\SEToolbox-1.205.024.1\SEToolbox.exe" 
CurrentDirectory: C:\Users\%USERNAME%\Desktop\SEToolbox-1.205.024.1
SEBinPath: D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64
SEBinVersion: 1.205.26
ProcessorCount: 32
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: False
CurrentUICulture: en-US
CurrentCulture: 
Times started total: 9
Times started since last reset: 9
Times started since game update: 9

Files:
2024-10-25T21:40:13.9168528-04:00	41,352	3.2.0.0	EmptyKeys.UserInterface.Core.dll
2024-10-25T21:40:10.4175116-04:00	654,728	3.2.0.0	EmptyKeys.UserInterface.dll
2024-10-25T21:40:10.4175116-04:00	292,744	0.1.1	HavokWrapper.dll
2024-10-26T22:23:50.9218193-04:00	591,872	2.25.0.0	HelixToolkit.Wpf.dll
2024-10-26T22:23:50.9417729-04:00	49,877		License.rtf
2024-10-26T23:15:33.7042013-04:00	0		log.txt
2024-10-26T22:23:50.9990140-04:00	285,696	3.0.1.0	log4net.dll
2024-10-26T22:23:51.0120294-04:00	146,464	1.1.135.29210	Microsoft.Xaml.Behaviors.dll
2024-07-31T00:17:28.4915888-04:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
2024-07-31T00:17:28.4915888-04:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
2024-10-26T22:23:51.0973660-04:00	1,389,056	13.0.1.0	Octokit.dll
2024-10-25T21:40:10.8592112-04:00	124,808	1.0.0.0	ProtoBuf.Net.Core.dll
2024-10-25T21:40:21.8493033-04:00	158,600	1.0.0.0	ProtoBuf.Net.dll
2024-10-25T21:40:10.7964922-04:00	112,520	1.0.0.0	Sandbox.Common.dll
2024-10-25T21:40:10.4185130-04:00	10,471,816	0.1.1	Sandbox.Game.dll
2024-10-25T21:40:10.4185130-04:00	1,056,136	0.1.1.0	Sandbox.Game.XmlSerializers.dll
2024-10-25T21:40:10.4185130-04:00	514,440	0.1.1	Sandbox.Graphics.dll
2024-10-25T21:40:20.1287617-04:00	36,744	1.0.0.0	Sandbox.RenderDirect.dll
2024-10-26T22:23:51.1158063-04:00	1,315,840	1.205.24.1	SEToolbox.exe
2024-10-26T22:23:51.1299085-04:00	2,010		SEToolbox.exe.config
2024-10-26T22:23:51.1404085-04:00	66,560	1.0.0.0	SEToolbox.ImageLibrary.dll
2024-10-26T22:23:51.1511262-04:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
2024-10-26T22:23:51.1609114-04:00	53,760	1.0.0.0	SEToolboxUpdate.exe
2024-10-25T21:40:10.4185130-04:00	296,328	4.2.1	SharpDX.Direct3D11.dll
2024-10-25T21:40:10.4190150-04:00	281,992	4.2.1	SharpDX.dll
2024-10-25T21:40:11.1542524-04:00	158,600	4.2.1	SharpDX.DXGI.dll
2024-10-25T21:40:12.0702854-04:00	42,888	1.0.0.0	SixLabors.Core.dll
2024-10-25T21:40:10.4190150-04:00	853,384	1.0.0.0	SixLabors.ImageSharp.dll
2024-10-25T21:40:10.4190150-04:00	2,126,216	1.0.0.0	SpaceEngineers.Game.dll
2024-10-25T21:40:10.4190150-04:00	4,090,248	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2024-10-25T21:40:10.4190150-04:00	10,629,000	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2024-10-25T21:40:10.4190150-04:00	384,392	20.1.0	Steamworks.NET.dll
2024-07-31T00:17:28.4930680-04:00	295,336	06.91.21.57	steam_api64.dll
2024-10-26T22:23:51.1736805-04:00	6		steam_appid.txt
2024-07-31T00:30:48.2966874-04:00	27,992	4.6.25519.03	System.Buffers.dll
2024-07-31T00:17:28.4930680-04:00	302,216	4.6.26515.06	System.Collections.Immutable.dll
2024-07-31T00:40:34.8762420-04:00	43,152	4.6.26515.06	System.ComponentModel.Annotations.dll
2024-10-25T21:40:10.4190150-04:00	326,024	1.0.102.0	System.Data.SQLite.dll
2024-07-31T00:42:02.8896512-04:00	148,720	4.6.27129.04	System.Memory.dll
2024-07-31T00:30:47.6306022-04:00	115,936	4.6.25519.03	System.Numerics.Vectors.dll
2024-07-31T00:38:32.0038932-04:00	23,600	4.6.26919.02	System.Runtime.CompilerServices.Unsafe.dll
2024-10-25T21:40:11.8219262-04:00	27,016	1.0.0.0	VRage.Ansel.dll
2024-10-25T21:40:20.3757388-04:00	78,216	1.0.0.0	VRage.Audio.dll
2024-10-25T21:40:10.4195149-04:00	662,920	1.0.0.0	VRage.dll
2024-10-25T21:40:10.4195149-04:00	4,183,432	1.0.0.0	VRage.Game.dll
2024-10-25T21:40:10.4195149-04:00	11,114,376	1.0.0.0	VRage.Game.XmlSerializers.dll
2024-10-25T21:40:13.3729472-04:00	108,936	1.0.0.0	VRage.Input.dll
2024-10-25T21:40:10.4195149-04:00	558,472	1.0.0.0	VRage.Library.dll
2024-10-25T21:40:10.4195149-04:00	593,800	1.0.0.0	VRage.Math.dll
2024-10-25T21:40:12.3817873-04:00	172,424	1.0.0.0	VRage.Math.XmlSerializers.dll
2024-10-25T21:40:10.9825637-04:00	103,816		VRage.Native.dll
2024-10-25T21:40:16.9500521-04:00	27,528	0.1.1	VRage.NativeWrapper.dll
2024-10-25T21:40:20.1287617-04:00	20,872	1.0.53.0	VRage.Network.dll
2024-10-25T21:40:10.4200161-04:00	419,208	1.0.0.0	VRage.Render.dll
2024-10-25T21:40:10.4200161-04:00	1,093,512	1.0.0.0	VRage.Render11.dll
2024-10-25T21:40:14.0417752-04:00	150,920	1.0.0.0	VRage.Scripting.dll
2024-10-25T21:40:14.2892205-04:00	134,024	1.0.0.0	VRage.Steam.dll
2024-10-25T21:40:16.5149958-04:00	133,512	1.0.0.0	VRage.XmlSerializers.dll
2024-10-26T22:23:51.2434075-04:00	90,624	3.10.0.0	WPFLocalizeExtension.dll
2024-10-26T22:23:51.2885796-04:00	36,864	2.1.3.0	XAMLMarkupExtensions.dll

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at VRage.Library.Collections.ThrowHelper.ThrowKeyNotFoundException()
   at VRage.Library.Collections.NativeDictionary`2.get_Item(TKey key)
   at Sandbox.Engine.Voxels.MySparseOctree.ReadRange[TOperator](TOperator& target, MyStorageDataTypeEnum type, Vector3I& writeOffset, Int32 lodIndex, Vector3I& minInLod, Vector3I& maxInLod)
   at Sandbox.Engine.Voxels.MyMicroOctreeLeaf.Sandbox.Engine.Voxels.IMyOctreeLeafNode.ReadRange(MyStorageData target, MyStorageDataTypeFlags types, Vector3I& writeOffset, Int32 lodIndex, Vector3I& minInLod, Vector3I& maxInLod, MyVoxelRequestFlags& flags)
   at Sandbox.Engine.Voxels.MyOctreeStorage.ReadRange(MyStorageData target, Vector3I& targetWriteOffset, MyStorageDataTypeFlags types, Int32 treeHeight, Dictionary`2 nodes, Dictionary`2 leaves, Int32 lodIndex, Vector3I& minInLod, Vector3I& maxInLod, MyVoxelRequestFlags& flags)
   at Sandbox.Engine.Voxels.MyOctreeStorage.ReadRangeInternal(MyStorageData target, Vector3I& targetWriteOffset, MyStorageDataTypeFlags dataToRead, Int32 lodIndex, Vector3I& lodVoxelCoordStart, Vector3I& lodVoxelCoordEnd, MyVoxelRequestFlags& flags)
   at Sandbox.Engine.Voxels.MyStorageBase.ReadRange(MyStorageData target, MyStorageDataTypeFlags dataToRead, Int32 lodIndex, Vector3I lodVoxelRangeMin, Vector3I lodVoxelRangeMax, MyVoxelRequestFlags& requestFlags)
   at Sandbox.Engine.Voxels.MyStorageBase.VRage.ModAPI.IMyStorage.ReadRange(MyStorageData target, MyStorageDataTypeFlags dataToRead, Int32 lodIndex, Vector3I lodVoxelRangeMin, Vector3I lodVoxelRangeMax)
   at SEToolbox.Interop.Asteroids.MyVoxelMap.CalcVoxelMaterialList()
   at SEToolbox.Models.Asteroids.AsteroidByteFiller.FillAsteroid(MyVoxelMap asteroid, IMyVoxelFillProperties fillProperties)
   at SEToolbox.ViewModels.GenerateVoxelFieldViewModel.BuildEntities(String[]& sourceVoxelFiles, MyObjectBuilder_EntityBase[]& sourceEntities)
   at SEToolbox.ViewModels.ExplorerViewModel.GenerateVoxelFieldExecuted()
   at SEToolbox.Services.DelegateCommand.Execute()
   at SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by mmusu3** [comment]
Fixed in 4121dff6878e1f296b7f5c1b875b13b0082e7034
